### PR TITLE
fix: Eliminate incorrect removal of reparented nodes

### LINKED ISSUE #572: Panic in accesskit_consumer when nodes are moved
To play along, open up [`process_changes` in `tree.rs`](https://github.com/AccessKit/accesskit/blob/daf5fafd63c42f62cc824a1f72e17aff1d102108/consumer/src/tree.rs#L286).

Here is my old state (`self.state`):

```rs
State {
    nodes: {
        #0: NodeState {
            parent_and_index: Some(
                ParentAndIndex(
                    #4294967296,
                    0,
                ),
            ),
            data: Node {
                role: Unknown,
                children: [
                    #1,
                ],
                label: "",
                description: "",
                value: "",
                tooltip: "",
                bounds: Rect { origin: (0.0, 0.0), size: 800.0W×600.0H },
            },
        },
        #1: NodeState {
            parent_and_index: Some(
                ParentAndIndex(
                    #0,
                    0,
                ),
            ),
            data: Node {
                role: Unknown,
                children: [
                    #2,
                ],
                label: "",
                description: "",
                value: "",
                tooltip: "",
                text_direction: LeftToRight,
                bounds: Rect { origin: (0.0, 0.0), size: 800.0W×600.0H },
            },
        },
        #2: NodeState {
            parent_and_index: Some(
                ParentAndIndex(
                    #1,
                    0,
                ),
            ),
            data: Node {
                role: Unknown,
                children: [
                    #3,
                ],
                label: "",
                description: "",
                value: "",
                tooltip: "",
                bounds: Rect { origin: (0.0, 0.0), size: 800.0W×600.0H },
            },
        },
        #4294967296: NodeState {
            parent_and_index: None,
            data: Node {
                role: Application,
                children: [
                    #0,
                ],
            },
        },
        #3: NodeState {
            parent_and_index: Some(
                ParentAndIndex(
                    #2,
                    0,
                ),
            ),
            data: Node {
                role: Section,
                label: "",
                description: "",
                value: "",
                tooltip: "",
                bounds: Rect { origin: (0.0, 0.0), size: 800.0W×600.0H },
            },
        },
    },
    data: Tree {
        root: #4294967296,
        toolkit_name: Some(
            "MyGreatToolkit",
        ),
        toolkit_version: Some(
            "0.1.0",
        ),
    },
    focus: #4294967296,
    is_host_focused: true,
}
```

This is the new tree I'm supplying (via the `update_factory`):

```rs
TreeUpdate {
    nodes: [
        (
            #3,
            Node {
                role: Section,
                children: [
                    #8,
                    #4,
                    #5,
                ],
                label: "",
                description: "",
                value: "",
                tooltip: "",
                bounds: Rect { origin: (0.0, 0.0), size: 800.0W×600.0H },
            },
        ),
        (
            #8,
            Node {
                role: Unknown,
                children: [
                    #9,
                    #10,
                ],
                label: "",
                description: "",
                value: "",
                tooltip: "",
                bounds: Rect { origin: (0.0, 0.0), size: 800.0W×56.0H },
            },
        ),
        (
            #4,
            Node {
                role: Image,
                label: "",
                description: "",
                value: "",
                tooltip: "",
                text_direction: LeftToRight,
                transform: Affine(
                    [
                        1.0,
                        0.0,
                        0.0,
                        1.0,
                        0.0,
                        56.0,
                    ],
                ),
                bounds: Rect { origin: (0.0, 0.0), size: 800.0W×544.0H },
            },
        ),
        (
            #5,
            Node {
                role: Unknown,
                children: [
                    #6,
                ],
                label: "",
                description: "",
                value: "",
                tooltip: "",
                transform: Affine(
                    [
                        1.0,
                        0.0,
                        0.0,
                        1.0,
                        480.0,
                        76.0,
                    ],
                ),
                bounds: Rect { origin: (0.0, 0.0), size: 300.0W×504.0H },
            },
        ),
        (
            #6,
            Node {
                role: Unknown,
                children: [
                    #7,
                ],
                label: "Inspector",
                description: "",
                value: "",
                tooltip: "",
                is_selected: false,
                text_direction: LeftToRight,
                bounds: Rect { origin: (0.0, 0.0), size: 300.0W×56.0H },
            },
        ),
        (
            #9,
            Node {
                role: Header,
                label: "3D Shape Viewer",
                description: "",
                value: "",
                tooltip: "",
                text_direction: LeftToRight,
                transform: Affine(
                    [
                        1.0,
                        0.0,
                        0.0,
                        1.0,
                        311.18359375,
                        14.0,
                    ],
                ),
                bounds: Rect { origin: (0.0, 0.0), size: 177.6328125W×28.0H },
            },
        ),
        (
            #10,
            Node {
                role: Button,
                actions: [
                    Click,
                    Focus,
                ],
                label: "",
                description: "",
                value: "",
                tooltip: "",
                transform: Affine(
                    [
                        1.0,
                        0.0,
                        0.0,
                        1.0,
                        760.0,
                        8.0,
                    ],
                ),
                bounds: Rect { origin: (0.0, 0.0), size: 40.0W×40.0H },
            },
        ),
        (
            #7,
            Node {
                role: Button,
                actions: [
                    Click,
                    Focus,
                ],
                label: "",
                description: "",
                value: "",
                tooltip: "",
                transform: Affine(
                    [
                        1.0,
                        0.0,
                        0.0,
                        1.0,
                        240.0,
                        8.0,
                    ],
                ),
                bounds: Rect { origin: (0.0, 0.0), size: 40.0W×40.0H },
            },
        ),
        (
            #4294967296,
            Node {
                role: Application,
                children: [
                    #3,
                ],
            },
        ),
    ],
    tree: Some(
        Tree {
            root: #4294967296,
            toolkit_name: Some(
                "MyGreatToolkit",
            ),
            toolkit_version: Some(
                "0.1.0",
            ),
        },
    ),
    focus: #4294967296,
}
```

Note that Node `0` was removed and replaced with Node `3` in the root node.

In [`tree.rs`](https://github.com/AccessKit/accesskit/blob/accesskit-v0.19.0/consumer/src/tree.rs) in the function `traverse_unreachable()`, Node `0` is removed and *all of its children*. The problem is, Node `3` is still part of the tree! So, all that remains in the internal representation is the root node.

This is the calculated change:

```rs
InternalChanges {
    added_node_ids: {
        #4,
        #6,
        #7,
        #8,
        #5,
        #9,
        #10,
    },
    updated_node_ids: {
        #3,
        #4294967296,
    },
    removed_node_ids: {
        #3,
        #8,
        #2,
        #9,
        #4,
        #10,
        #7,
        #5,
        #1,
        #6,
        #0,
    },
}
```

Note how Node `3` is in updated and removed, which doesn't make sense.

So, the code then panics in

https://github.com/AccessKit/accesskit/blob/daf5fafd63c42f62cc824a1f72e17aff1d102108/consumer/src/tree.rs#L293

because the updated node isn't actually found in `next_state`. Depending on what exactly happened, it could also panic in

https://github.com/AccessKit/accesskit/blob/daf5fafd63c42f62cc824a1f72e17aff1d102108/consumer/src/tree.rs#L288

If the node is both in `added_node_ids` and `removed_node_ids`.

I think what happens is that my UI framework moves semantic nodes between parents, and AccessKit assumes that this doesn't happen.

### PR DESCRIPTION
**Pull request by mwcampbell**
Fixes #572.

### CODE REVIEW

File: consumer/src/tree.rs [hunk 1]
```diff
@@ -74,14 +75,11 @@ impl State {
...
             unreachable.remove(&node_id);
 
-            let mut seen_child_ids = HashSet::with_capacity(node_data.children().len());
             for (child_index, child_id) in node_data.children().iter().enumerate() {
                 if seen_child_ids.contains(child_id) {
-                    panic!(
-                        "Node {:?} of TreeUpdate includes duplicate child {:?};",
-                        node_id, child_id
-                    );
+                    panic!("TreeUpdate includes duplicate child {:?};", child_id);
```
Comment (DataTriny) [inline consumer/src/tree.rs:80]:
```suggestion
                    panic!("TreeUpdate includes duplicate child {:?}", child_id);
```

**Review by DataTriny — CHANGES_REQUESTED** [review]
Just one minor suggestion on the panic message.
